FROM golang:1.22-alpine

RUN apk add --no-cache gcc musl-dev git && \
    go install github.com/air-verse/air@latest

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
